version: "3"
services:
  postgres:
    image: postgres:12.9
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/data/postgres
      - postgresdbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=synthesia
      - POSTGRES_PASSWORD=synthesia
      - POSTGRES_DB=synthesia
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network

  webserver:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    restart: always
    ports:
      - "8000:4000"
    command: bash -c "npm run migrate && npm run webserver"
    volumes:
      - .:/src
    networks:
      - app-network

  sign-job-worker:
    build: .
    depends_on:
      - postgres
      - redis
      - webserver
    restart: always
    command: npm run sign-job-worker
    networks:
      - app-network
  webhook-worker:
    build: .
    depends_on:
      - postgres
      - redis
      - webserver
    restart: always
    command: npm run webhook-worker
    networks:
      - app-network

volumes:
  postgresdata:
    driver: local
  postgresdbdata:
    driver: local
  redisdata:
    driver: local

networks:
  app-network:
    driver: bridge
