const JOB_QUEUE_NAME = "API_CALLER";
const JOB_NAME = "RETRY_SIGN_CALL";
const WEBHOOK_QUEUE_NAME = "WEBHOOK_CALLER";
const WEBHOOK_EVENT = "WEBHOOK_CALL";

module.exports = {
  JOB_QUEUE_NAME,
  WEBHOOK_QUEUE_NAME,
  WEBHOOK_EVENT,
  JOB_NAME,
};
